"use client";

import "./globals.css";
import type { Metadata } from "next";
import { Provider } from "react-redux";
import { PersistGate } from "redux-persist/integration/react";
import { Poppins } from "next/font/google";

import { store } from "@src/redux/store";
import { persistStore } from "redux-persist";
import firebaseInit from "@src/firebase/config";

const poppins = Poppins({
  subsets: ["latin-ext"],
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

firebaseInit();
const persistor = persistStore(store);

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Provider store={store}>
          <PersistGate persistor={persistor} loading={null}>
            {children}
          </PersistGate>
        </Provider>
      </body>
    </html>
  );
}
