const CHAPTERS = [
  "Arizona State University",
  "Augusta University",
  "Carnegie Mellon",
  "Case Western Reserve University",
  "Chaminade University of Honolulu",
  "Claremont Colleges",
  "Colorado School of Mines",
  "Columbia University",
  "Cornell University",
  "CSU Long Beach",
  "Dalhousie University",
  "Duke University",
  "Emory University",
  "Florida Institute of Technology",
  "Florida State University",
  "Fordham University",
  "Georgetown University",
  "Georgia Tech",
  "Harvard University",
  "Howard University",
  "Hunter College in New York City",
  "Indiana University Bloomington",
  "Johns Hopkins University",
  "Lawrence High School",
  "Louisiana State University",
  "Loyola University Chicago",
  "Loyola University New Orleans",
  "McGill University",
  "McMaster University",
  "Michigan State University",
  "Midwestern State University",
  "New Canaan High School",
  "NIH Post-Bacc program",
  "Northeastern University",
  "Notre Dame",
  "New York University",
  "Oakland University",
  "Oregon State University",
  "Princeton Day High School",
  "Purdue University",
  "Redeemer University",
  "Rutgers New Brunswick",
  "Rutgers University Newark, School of Health Professions",
  "Smith College",
  "Stony Brook University",
  "Syracuse University",
  "Texas Christian University",
  "Tufts University",
  "UC Berkeley",
  "UC Davis",
  "UCI",
  "UCLA",
  "UCR",
  "UCSB",
  "UCSD",
  "University of Alabama at Birmingham",
  "University of British Columbia at Okanagan",
  "University of Florida",
  "University of Georgia",
  "University of Maryland",
  "University of Miami",
  "University of Michigan",
  "University of Pennsylvania",
  "University of Portland",
  "University of Tennessee",
  "University of Texas - San Antonio",
  "University of Texas Dallas",
  "University of Washington",
  "University of Waterloo",
  "University of Western Ontario",
  "University of Southern California",
  "University of Texas Austin",
  "Vanderbilt University",
  "Wake Forest",
  "Washington and Lee University",
  "Washington University in St. Louis",
].map((chapter) => ({
  value: chapter,
  displayValue: chapter,
}));

export default CHAPTERS;
