import { ITableEntry } from "@/common_utils/types";

export const sampleUsers: ITableEntry[] = [
  {
    name: "John Doe",
    patientDetails: {
      birthdate: "1990-01-01",
      secondaryContactName: "Jane Doe",
      secondaryContactPhone: "555-222-1515",
      additionalAffiliation: "Patient visits Florida chapter every Tuesday",
    },
    status: true,
    email: "john.doe@example.com",
    chapter: "Georgia Institute of Technology",
    location: {
      country: "USA",
      state: "California",
      city: "Los Angeles",
    },
    startDate: "2020-05-05",
  },
  {
    name: "Jane Smith",
    patientDetails: {
      birthdate: "1992-02-02",
      secondaryContactName: "Ella Smith",
      secondaryContactPhone: "555-334-7890",
      additionalAffiliation: "Patient visits Florida chapter every Tuesday",
    },
    status: true,
    email: "jane.smith@example.com",
    chapter: "Toronto Central",
    location: {
      country: "Canada",
      state: "Ontario",
      city: "Toronto",
    },
    startDate: "2021-01-10",
  },
  {
    name: "Alice Johnson",
    patientDetails: {
      birthdate: "1985-03-03",
      secondaryContactName: "Michael Johnson",
      secondaryContactPhone: "555-456-7890",
      additionalAffiliation: "Patient visits Florida chapter every Tuesday",
    },
    status: false,
    email: "alice.johnson@example.com",
    chapter: "London Health Sciences Center",
    location: {
      country: "UK",
      state: "England",
      city: "London",
    },
    startDate: "2021-02-20",
  },
  {
    name: "Bob Brown",
    patientDetails: {
      birthdate: "1987-04-04",
      secondaryContactName: "Linda Brown",
      secondaryContactPhone: "555-567-8901",
      additionalAffiliation: "Patient visits Florida chapter every Tuesday",
    },
    status: true,
    email: "bob.brown@example.com",
    chapter: "Sydney Medical Center",
    location: {
      country: "Australia",
      state: "New South Wales",
      city: "Sydney",
    },
    startDate: "2021-03-15",
  },
  {
    name: "Charlie Davis",
    patientDetails: {
      birthdate: "1995-05-05",
      secondaryContactName: "Sarah Davis",
      secondaryContactPhone: "555-678-9012",
      additionalAffiliation: "Patient visits Florida chapter every Tuesday",
    },
    status: false,
    email: "charlie.davis@example.com",
    chapter: "Mumbai Health Forum",
    location: {
      country: "India",
      state: "Maharashtra",
      city: "Mumbai",
    },
    startDate: "2021-04-22",
  },
  {
    name: "Diana Evans",
    patientDetails: {
      birthdate: "1980-06-06",
      secondaryContactName: "Peter Evans",
      secondaryContactPhone: "555-789-0123",
      additionalAffiliation: "Patient visits Florida chapter every Tuesday",
    },
    status: true,
    email: "diana.evans@example.com",
    chapter: "Rio de Janeiro Health Institute",
    location: {
      country: "Brazil",
      state: "Rio de Janeiro",
      city: "Rio de Janeiro",
    },
    startDate: "2021-05-30",
  },
  {
    name: "Evan Foster",
    patientDetails: {
      birthdate: "1988-07-07",
      secondaryContactName: "Julia Foster",
      secondaryContactPhone: "555-890-1234",
      additionalAffiliation: "Patient visits Florida chapter every Tuesday",
    },
    status: false,
    email: "evan.foster@example.com",
    chapter: "Bavarian Medical Society",
    location: {
      country: "Germany",
      state: "Bavaria",
      city: "Munich",
    },
    startDate: "2021-07-14",
  },
  {
    name: "Fiona Green",
    patientDetails: {
      birthdate: "1993-08-08",
      secondaryContactName: "Mark Green",
      secondaryContactPhone: "555-901-2345",
      additionalAffiliation: "Patient visits Florida chapter every Tuesday",
    },
    status: true,
    email: "fiona.green@example.com",
    chapter: "Johannesburg Health Chapter",
    location: {
      country: "South Africa",
      state: "Gauteng",
      city: "Johannesburg",
    },
    startDate: "2021-08-28",
  },
  {
    name: "George Harris",
    patientDetails: {
      birthdate: "1975-09-09",
      secondaryContactName: "Lucy Harris",
      secondaryContactPhone: "555-012-3456",
      additionalAffiliation: "Patient visits Florida chapter every Tuesday",
    },
    status: true,
    email: "george.harris@example.com",
    chapter: "Tokyo Medical Association",
    location: {
      country: "Japan",
      state: "Tokyo",
      city: "Tokyo",
    },
    startDate: "2021-09-12",
  },
  {
    name: "Hannah Adams",
    patientDetails: {
      birthdate: "1997-10-10",
      secondaryContactName: "Oliver Adams",
      secondaryContactPhone: "555-123-4567",
      additionalAffiliation: "Patient visits Florida chapter every Tuesday",
    },
    status: false,
    email: "hannah.adams@example.com",
    chapter: "Wellington Health Services",
    location: {
      country: "New Zealand",
      state: "Wellington",
      city: "Wellington",
    },
    startDate: "2021-10-05",
  },
];
