name: Average Metrics
on: workflow_dispatch

jobs:
  averageWeek:
    name: Average Metrics
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Post Request
        run:
          curl -X POST \ https://app.netlify.com/sites/brain-exercise-initiative-analytics/deploys/6513b839abba8f0009d15c14/api/patient/internal/average-stats
          -f body=' '
        env:
          secret: ${{ secrets.INTERNAL_AVERAGE_SECRET }}

